### ISSUE TITLE
Не устанавливается на Windows 7 RUS

### ISSUE THREAD

**Issue by MinistrBob** [zt50tz/yandex-connect#1]
На русских версиях Windows при установке возникает ошибка, потому что по умолчанию используется кодировка 1251

```
(venv) d:\YandexDisk\Python\WORK\GTMail\venv\Scripts>pip install yandex-connect
Collecting yandex-connect
  Using cached https://files.pythonhosted.org/packages/99/e7/eafe4d1ce9fc8e8dc745a3b90fef97b2de07f630f852794c4f82261eadc
a/yandex_connect-0.25b0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\TEMP\pip-install-fnelme13\yandex-connect\setup.py", line 8, in <module>
        long_description = f.read()
      File "C:\Program Files\Python37\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 3156: character maps to <undefined>
```

Лучше явно указывать кодировку при открытии файлов из setup.py. Например так:

`long_description=open(join(dirname(__file__), 'README.md'), encoding="utf-8").read()`

**Comment by zt50tz** [comment]
Попробуйте сейчас, пожалуйста. Должно сработать.

**Comment by MinistrBob** [comment]
Да, сейчас работает.
 
От: Alexeev Nick [mailto:notifications@github.com] 
Отправлено: 28 мая 2019 г. 23:34
Кому: zt50tz/yandex-connect
Копия: Бобровский Дмитрий; Author
Тема: Re: [zt50tz/yandex-connect] Не устанавливается на Windows 7 RUS (#1)
 
Попробуйте сейчас, пожалуйста. Должно сработать.

**Comment by MaximMukhametov** [comment]
Не пойму куда это прописать ? long_description=open(join(dirname(__file__), 'README.md'), encoding="utf-8").read()

**Comment by zt50tz** [comment]
Ошибка исправлена, в pip версия обновлена. 
Приведите лог ошибки, которая у вас выводится, пожалуйста.

**Comment by MaximMukhametov** [comment]
спасибо ,разобрался, была похожая ошибка при попытке pip install django-google-maps . В итоге скачал файл установщик .tar.gz разархивировал, редактировал setup.py (добавил encoding="utf-8") и установил вручную :)

**Comment by zt50tz** [comment]
Так а ошибка то сохранилась получается при установке в автоматическом режиме?
Не могли бы вы предоставить лог ошибки, пожалуйста.

**Comment by MaximMukhametov** [comment]
(venv) C:\Users\Frodo\PycharmProjects\googlemap_sample>pip install django-google-maps
Collecting django-google-maps
  Using cached https://files.pythonhosted.org/packages/ca/5d/29f286e1a0178adc7227187875af14a9df60dac28a70095a4b3a5db421aa/django-google-maps-0.12.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Frodo\AppData\Local\Temp\pip-install-89q_q3_1\django-google-maps\setup.py", line 6, in <module>
        LONG_DESCRIPTION = open(README, 'r').read()
      File "C:\Users\Frodo\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2775: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Frodo\AppData\Local\Temp\pip-install-89q_q3_1\django-google-maps\

**Comment by zt50tz** [comment]
Вы указали лог для django-google-maps. А не с пакетом “yandex-connect” :(
Я проверил, заливал ли я свежую версию в pypi, вроде она там свежая и не должно быть похожей ошибки.
