### ISSUE TITLE
Небольшие доработки

### ISSUE THREAD

**Issue by Barmagloth** [zt50tz/yandex-connect#4]
Использовал JupyterLab, ядро 3.8

В base.py пришлось изменить encodestring на encodebytes (т.к. encodestring в 3 версии питона deprecated):
28    auth_base64 = base64.encodebytes(auth.encode()).decode("utf-8")

Возможно, поэтому (но это не точно) в directory.py в user_id_check() если user_id задан текстом, съедается последний символ. Исправил, тупо добавив пробел:
96                user_id = self.user_get_id_by_nickname(user_id+' ')

**Comment by zt50tz** [comment]
Я прошу прощения, ужасно плохо со временем.
Спасибо большое, что написали. Надеюсь, что в самое ближайшее время внесу коррективы.

**Comment by zt50tz** [comment]
Лучше поздно, чем никогда :)

1) Теперь проверяется, есть ли метод `encodebytes` в `base64` и если он есть используется он.
2) Проблема была в определении почта передается или просто nickname.  И если почта, то образалось то, что идет после знака "@". `directory.py:75` должно быть `> -1`, а не просто логическое условие, которое проходится на возврат значения "-1".

Спасибо вам.
